### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by sanjayhallan** [jonsamwell/angular-auto-validate#92]
Hi,

When I load jcs-auto-validate.js via HTML in a chrome for both version 1.18.13 and 1.18.14 the console prints out:
TypeError: Converting circular structure to JSON
    at Object.stringify (native)

Is anyone else experiencing this? before I add some more detail.

I am referencing via maven webjar using wro4j for minification. 

Thanks
Sanjay

**Comment by jonsamwell** [comment]
Hi,

I don't think the library does an Object.stringify anywhere?

In either case I'd upgrade to the latest release (v1.18.16) and still if this is still an issue.  If it is could you do up a reproducing plunker and I'll get it fixed :-)

**Comment by sanjayhallan** [comment]
Its also happening with v1.18.16. 1.18.6 works fine. But reproducing it is inconsistent... grrr

**Comment by jonsamwell** [comment]
What the stack trace when it happens?  Does it only happen when minified?

**Comment by jonsamwell** [comment]
Any further information?

**Comment by jonsamwell** [comment]
Closing as no further information provided.  Please feel free to re-open it a reproducing Plunker is provided

**Comment by surendrand** [comment]
I am facing this issue. I just included 'jcs-autoValidate' in my angular module and refreshed the page. 
Following is the stacktrace

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at toJson (http://localhost:63342/Angular/js/angular.js:1234:15)
    at http://localhost:63342/Angular/js/angular.js:19067:12
    at fn (eval at <anonymous> (http://localhost:63342/Angular/js/angular.js:13322:15), <anonymous>:4:156)
    at regularInterceptedExpression (http://localhost:63342/Angular/js/angular.js:14402:21)
    at Object.expressionInputWatch [as get] (http://localhost:63342/Angular/js/angular.js:14304:26)
    at Scope.$digest (http://localhost:63342/Angular/js/angular.js:15818:40)
    at Scope.$apply (http://localhost:63342/Angular/js/angular.js:16097:24)
    at bootstrapApply (http://localhost:63342/Angular/js/angular.js:1660:15)
    at Object.invoke (http://localhost:63342/Angular/js/angular.js:4478:17)
TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at toJson (http://localhost:63342/Angular/js/angular.js:1234:15)
    at http://localhost:63342/Angular/js/angular.js:19067:12
    at fn (eval at <anonymous> (http://localhost:63342/Angular/js/angular.js:13322:15), <anonymous>:4:156)
    at regularInterceptedExpression (http://localhost:63342/Angular/js/angular.js:14402:21)
    at Object.expressionInputWatch [as get] (http://localhost:63342/Angular/js/angular.js:14304:26)
    at Scope.$digest (http://localhost:63342/Angular/js/angular.js:15818:40)
    at Scope.$apply (http://localhost:63342/Angular/js/angular.js:16097:24)
    at http://localhost:63342/Angular/js/angular.js:17864:36
    at completeOutstandingRequest (http://localhost:63342/Angular/js/angular.js:5507:10)

**Comment by jonsamwell** [comment]
Could you do a reproducing Plunker?

**Comment by surendrand** [comment]
Please find the attached project

**Comment by surendrand** [comment]
can be reproduced from
https://github.com/surendrand/angular-auto-validate-issue.git

**Comment by jonsamwell** [comment]
Fixed in v1.19.0
